font_name: Liberation Mono
font_size: 14

refresh_interval: 1
refresh_timeout: 10
flapping_detection_interval: 60

title:       Services
label_ok:    Available
label_error: Unavailable
color_ok:    green
color_error: red

window_gravity: bottom_right
edge_x_offset: 10
edge_y_offset: 50

notification_title: Status change in %s
notification_text:  The service is now %s
notification_timeout: ~

background_rgba:
    red:   0.0
    green: 0.0
    blue:  0.0
    alpha: 0.9

services:
    - name: Router admin panel
      address: 192.168.0.1
      port: 80

    - name: Something
      address: 192.168.0.211
      port: 80
      refresh_timeout: 5
      refresh_interval: 10

    - name: Charon
      address: 127.0.0.1
      port: 5000  

    - name: DuckDuckGo
      address: duckduckgo.com
      port: 80
